### ISSUE TITLE
Turn into a Library

### ISSUE THREAD

**Issue by lemonlambda** [frederickjjoubert/bevy_ecs_tilemap_autotile_example#1]
Wondering if you could turn this into a library? It would probably be a lot of work and I'm not exactly knowledgeable on the subject, so I was wondering if you could do it.

**Comment by frederickjjoubert** [comment]
I made an attempt with @bzm3r to create a more general-purpose solution but it's beyond my level of expertise and we didn't pursue it further - so no.

**Comment by lemonlambda** [comment]
Alright thank you.
